version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:19.7.0
    steps:
      - checkout

workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
